### ISSUE TITLE
Using SLURM, 2 nodes each with 4 GPUs [problem]

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#1039]
Hi,
  I can't get Sockeye to train using `SLURM` and 2 nodes each with 4 GPUs.  I found examples for running `Sockeye` on a single node with multiple GPUs [here](https://awslabs.github.io/sockeye/tutorials/wmt_large.html).
* Do I need to use `srun torchrun` or simply `torchrun` is enough?
* What about `torchrun --nnodes=X`, do I need to use it and if so what value does it need to be set at?
* What about `torchrun --nproc_per_node=Y`, do I need to use it and if so what value does it need to be set at?
* Do I need to set `--master-addr` and `--master-port`?
* Should my `slurm` script call a helper script for this task or can I do all of this inside a single `slurm` script?

# SLURM
```bash
#SBATCH --gres=gpu:4
#SBATCH --time=12:00:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6
#SBATCH --mem=96G
```

# Sockeye

```bash
export HOST_NODE_ADDR=$SLURMD_NODENAME:$(($RANDOM % 20000 + 10000))
time torchrun \
      --no_python \
      --nnodes=$SLURM_NNODES \
      --nproc_per_node=$SLURM_TASKS_PER_NODE \
      --rdzv_id=$SLURM_JOBID \
      --rdzv_backend=c10d \
      --rdzv_endpoint=$HOST_NODE_ADDR \
      sockeye-train \
         --dist \
         --quiet-secondary-workers \
         --config=model_config.yaml \
         $train_corpora_opt &
    wait
```

# Single Node/Multiple GPUs
I can get `Sockeye` to train on a single node but using multiple GPUs using the following.

```bash
time torchrun \
      --no_python \
      --nproc_per_node=$SLURM_TASKS_PER_NODE \
      sockeye-train \
         --dist \
         --quiet-secondary-workers \
         --config=model_config.yaml \
         $train_corpora_opt &
    wait
```

I've tried some many different ways without success.  What is the correct way of using Sockeye on multi-node, multi-gpus?

**Comment by mjdenkowski** [comment]
Hi @SamuelLarkin,

Sockeye's distributed training runs with `torchrun`.  A simple way to launch multi-node training is to run the following on the individual nodes:
`torchrun --nnodes 2 --nproc_per_node 1 --master_addr 192.168.0.1 --master_port 9000 --node_rank 0 ...`
`torchrun --nnodes 2 --nproc_per_node 1 --master_addr 192.168.0.1 --master_port 9000 --node_rank 1 ...`
The number of nodes, number of processes, master address, and master port change with the job setup.  The node rank is different for each node.  Hosts should be able to connect to each other on the specified port and use a shared filesystem.

Right now there are some issues with `torch.distributed`'s  utility functions for synchronizing state that are blocking Sockeye's multi-node training in some environments.  Single node multi-process training is unaffected.

Generally training on 8 GPUs on a single node is a good value for standard models.  Are you looking at training something substantially larger?

**Comment by SamuelLarkin** [comment]
Thanks for the info.
Unfortunately, our nodes only have 4 GPUs.  Training on a single node with all 4 GPUs works.
I'm actually trying to prepare work for a future project that will surely benefit from multi-node, multi-gpus training.
My last attempt was using a `slurm` script that `srun` a `train.sh` but it didn't succeed.

I noticed that you are `--nproc_per_node=1` and I effectively do `--nproc_per_node=4`.  I'll try your setup.

# train.slurm
```bash
#!/bin/bash
#SBATCH --gres=gpu:4
#SBATCH --time=12:00:00
#SBATCH --wait-all-nodes=1
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6
#SBATCH --mem=96G

readonly master_addr_job=$SLURMD_NODENAME
readonly master_port_job=$(($RANDOM % 20000 + 10000))

srun \
  --export=ALL,MASTER_ADDR=$master_addr_job,MASTER_PORT=$master_port_job \
  bash $(which train.sh) &
wait
```

# train.sh
This is only a snippet of `train.sh`
```bash
      time torchrun \
            --no_python \
            --nnodes=$SLURM_NNODES \
            --nproc_per_node=$SLURM_TASKS_PER_NODE \
            --node_rank=$SLURM_NODEID \
            --rdzv_id=$SLURM_JOBID \
            --rdzv_backend=c10d \
            --rdzv_endpoint=$HOST_NODE_ADDR \
            --master_addr=$MASTER_ADDR \
            --master_port=$MASTER_PORT \
            sockeye-train \
               --dist \
               --quiet-secondary-workers \
               --config=model_config.yaml
```

Using my last setup, it looks like training is about to start and I get the following error:
```bash
[INFO:sockeye.data_io] Shuffling the shards.
[INFO:sockeye.data_io] Loading shard corpora/prepared.shared_vocab/shard.00008.
[INFO:sockeye.data_io] Replicating bucket of 1 sentence(s) 2 times to cover 2 splits.
[INFO:sockeye.data_io] Replicating bucket of 1 sentence(s) 2 times to cover 2 splits.
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
...
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 637
    raise RendezvousTimeoutError()
torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
```
From what I can decipher, there seems to be a communication problem for the rendez-vous but I don't know what is causing this.

Note that I'm using a shared filesystem and nodes are able to talk to each other.

**Comment by SamuelLarkin** [comment]
I've changed the `master_addr` to be an ip and not a name and I'm getting a bit further.  Now, I'm getting errors about nccl.  I wonder if my NCCL is too old or something?

Also, I find strange that the hosts in the following error, are all from the master node for all ranks.  I was expecting to get 4 from the master and 4 from the only work.

```
  time      : 2022-04-06_11:46:18
  host      : cn102.head.cm.res.nrc.gc.ca
  rank      : 7 (local_rank: 3)
  exitcode  : 1 (pid: 5002)
  error_file: /tmp/torchelastic_ir8uv3i5/94704_fa9b4eq6/attempt_0/3/error.json
  traceback : Traceback (most recent call last):
    File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line
      return f(*args, **kwargs)
    File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/sockeye/train.py", line 872, in train
      resume_training = check_resume(args, output_folder)
    File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/sockeye/train.py", line 179, in check_resume
      torch.distributed.barrier()
    File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
      work = default_pg.barrier(opts=opts)
  RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1634272068694/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, invalid usage, NCCL version 21.0.3
  ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
```

```
nccl=2.11.4.1=h5c60f85_2
```

**Comment by mjdenkowski** [comment]
We found a potential root cause for this issue.  At runtime, NCCL uses random ports to create connections between clients ([#388](https://github.com/NVIDIA/nccl/issues/388)).  These are different from `--master_port` and cannot be specified in advance by the user.  If these ports are blocked, processes can still create connections on the master port with `torch.distributed` and start training, but anything that uses NCCL (e.g., `barrier()`) will fail.  This causes various `torch.distributed` utility functions to work for local multi-process training but fail for multi-node training on some networks.

Can you open all TCP ports (0-65535) among the nodes in your cluster?

For the `torchrun` command, it's actually not necessary to specify `--rdzv_id`, `--rdzv_backend`, or `--rdzv_endpoint`.  You can also set `--nproc_per_node` to the number of GPUs per node for your cluster (`4`).

**Comment by SamuelLarkin** [comment]
Thanks a lot for the hint.  I've asked and our cluster's current setup only allows port ~32k-60k.  I'll ask them to widen the port range and try this again.

**Comment by SamuelLarkin** [comment]
The allowed port range on the cluster was limited.  Here's an update after extending the allowed port range.

I've dialed down to 2 nodes with one task each instead of 2 nodes with 4 tasks each.

# Observations
I can see, using `htop` & `nvidia-smi` that a `torchrun` process starts on each node.  The odd thing is that on the master node aka node_rank=0, `nvidia-smi` shows that a process is running but that process is quite suspicious as it is only using 1G/32G of gpu RAM when I expect it to be closer to full usage of memory.  The second odd thing is that on the worker node aka node_rank=1, `nvidia-smi` shows 2 processes, each using ~1G but they are doing 0% work.

On both node I see indications that NCCL was initialized
```
cn103:13998:13998 [1] NCCL INFO Bootstrap : Using ib0:10.11.0.103<0>
cn103:13998:13998 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
cn103:13998:13998 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.11.0.103<0>
cn103:13998:13998 [1] NCCL INFO Using network IB
cn103:13998:14044 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
cn103:13998:14044 [1] NCCL INFO Channel 00 : 0[89000] -> 1[8a000] [receive] via NET/IB/0
cn103:13998:14044 [1] NCCL INFO Channel 01 : 0[89000] -> 1[8a000] [receive] via NET/IB/0
cn103:13998:14044 [1] NCCL INFO Channel 00 : 1[8a000] -> 0[89000] [send] via NET/IB/0
cn103:13998:14044 [1] NCCL INFO Channel 01 : 1[8a000] -> 0[89000] [send] via NET/IB/0
cn103:13998:14044 [1] NCCL INFO Connected all rings
cn103:13998:14044 [1] NCCL INFO Connected all trees
cn103:13998:14044 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
cn103:13998:14044 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
cn103:13998:14044 [1] NCCL INFO comm 0x7fb080002010 rank 1 nranks 2 cudaDev 1 busId 8a000 - Init COMPLETE
```

On the master node, we can see that sockeye has begun but I don't see any indication that sockeye was started on the worker.
```
...
[INFO:sockeye.data_io] Shuffling the shards.
[INFO:sockeye.data_io] Loading shard corpora/prepared.shared_vocab/shard.00008.
[INFO:sockeye.data_io] Replicating bucket of 1 sentence(s) 2 times to cover 2 splits.
```
## On Master
time torchrun --no_python --nnodes=2 --nproc_per_node=1 --node_rank=0 --rdzv_id=94724 --rdzv_backend=c10d --rdzv_endpoint=cn102:33642 --master_addr=cn102 --master_port=33641 sockeye-train --dist --quiet-secondary-workers --config=model_config.yaml
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   31C    P0    62W / 300W |   1290MiB / 32768MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   32C    P0    43W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   30C    P0    43W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   31C    P0    42W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     24676      C   ...ckeye-3.1.0/bin/python3.8     1287MiB |
+-----------------------------------------------------------------------------+

## Worker
time torchrun --no_python --nnodes=2 --nproc_per_node=1 --node_rank=1 --rdzv_id=94724 --rdzv_backend=c10d --rdzv_endpoint=cn102:33642 --master_addr=cn102 --master_port=33641 sockeye-train --dist --quiet-secondary-workers --config=model_config.yaml
|   0  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   31C    P0    53W / 300W |   1280MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P0    56W / 300W |   1290MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   29C    P0    42W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   32C    P0    42W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     12458      C   ...ckeye-3.1.0/bin/python3.8     1277MiB |
|    1   N/A  N/A     12458      C   ...ckeye-3.1.0/bin/python3.8     1287MiB |
+-----------------------------------------------------------------------------+


# train.slurm
```bash
#SBATCH --gres=gpu:4
#SBATCH --time=12:00:00
#SBATCH --wait-all-nodes=1
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=96G

readonly srun='srun --output=%x-%j.%t.out'
readonly master_addr_job=$SLURMD_NODENAME
readonly master_port_job=$(($RANDOM % 10000 + 32769))

echo srun \
  --export=ALL,MASTER_ADDR=$master_addr_job,MASTER_PORT=$master_port_job \
  bash $(which train.sh)

$srun \
  --export=ALL,MASTER_ADDR=$master_addr_job,MASTER_PORT=$master_port_job \
  bash $(which train.sh) &
wait
```

# train.sh
```bash
time torchrun \
        --no_python \
        --nnodes=$SLURM_NNODES \
        --nproc_per_node=$SLURM_TASKS_PER_NODE \
        --node_rank=$SLURM_NODEID \
        --master_addr=$MASTER_ADDR \
        --master_port=$MASTER_PORT \
        sockeye-train \
           --dist \
           --quiet-secondary-workers \
           --config=model_config.yaml
```

**Comment by mjdenkowski** [comment]
Have you tried running the commands without `--rdzv_id=... --rdzv_backend=... --rdzv_endpoint=...`?

Can you run the commands using an IP address for `--master_addr`?

I've also pushed a [dist_debug](https://github.com/awslabs/sockeye/tree/dist_debug) branch that adds print statements before and after operations that are known to have issues when ports are blocked.  Running training with that branch may narrow down what's causing the issue.

**Comment by SamuelLarkin** [comment]
Thanks for your help @mjdenkowski !
I've tried with and without `--rdzv_id=... --rdzv_backend=... --rdzv_endpoint=...` and with a fixed ip.

The command is:
```bash
time \
  torchrun \
    --no_python \
    --nnodes=2 \
    --nproc_per_node=1 \
    --node_rank=0 \
    --master_addr=10.10.0.104 \
    --master_port=42314 \
    --rdzv_id=94761 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=10.10.0.104:42315 \
    sockeye-train \
      --dist \
      --quiet-secondary-workers \
      --config=model_config.yaml
```

The result is the same.

# Master
The master starts one nvidia process that is using 1G and 100% GPU usage.  I see one `sockeye-train` at 200% even though I provide 6 cpus per task and all that process is doing indefinitely is:
```
clock_gettime(CLOCK_MONOTONIC_RAW, {tv_sec=4222831, tv_nsec=568585236}) = 0
```

Last thing in the log is
```
cn102:5924:5924 [0] NCCL INFO Bootstrap : Using ib0:10.11.0.102<0>
cn102:5924:5924 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
cn102:5924:5924 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.11.0.102<0>
cn102:5924:5924 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda11.3
cn102:5924:5975 [0] NCCL INFO Channel 00/02 :    0   1
cn102:5924:5975 [0] NCCL INFO Channel 01/02 :    0   1
cn102:5924:5975 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
cn102:5924:5975 [0] NCCL INFO Channel 00 : 1[8a000] -> 0[89000] [receive] via NET/IB/0
cn102:5924:5975 [0] NCCL INFO Channel 01 : 1[8a000] -> 0[89000] [receive] via NET/IB/0
cn102:5924:5975 [0] NCCL INFO Channel 00 : 0[89000] -> 1[8a000] [send] via NET/IB/0
cn102:5924:5975 [0] NCCL INFO Channel 01 : 0[89000] -> 1[8a000] [send] via NET/IB/0
cn102:5924:5975 [0] NCCL INFO Connected all rings
cn102:5924:5975 [0] NCCL INFO Connected all trees
cn102:5924:5975 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
cn102:5924:5975 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
cn102:5924:5975 [0] NCCL INFO comm 0x7fe124002010 rank 0 nranks 2 cudaDev 0 busId 89000 - Init COMPLETE
cn102:5924:5924 [0] NCCL INFO Launch mode Parallel
[INFO:sockeye.utils] Sockeye: 3.1.7, commit b24b2c1352e71659fd61e49f9384f255e4161e5a, path /gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.7/lib/python3.8/
[INFO:sockeye.utils] PyTorch: 1.10.0 (/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.7/lib/python3.8/site-packages/torch/__init__.py)

...

[INFO:sockeye.data_io] Shuffling the shards.
[INFO:sockeye.data_io] Loading shard corpora/prepared.shared_vocab/shard.00008.
[INFO:sockeye.data_io] Replicating bucket of 1 sentence(s) 2 times to cover 2 splits.
```

# Worker
The worker is spawning two nvidia processes and one `torchrun` and one `sockeye-train` process where none are doing any cpu work nor gpu work.  Doing `strace`, I see:
```
recvfrom(4,
```

Last thing in the log
```
cn103:5367:5367 [1] NCCL INFO Bootstrap : Using ib0:10.11.0.103<0>
cn103:5367:5367 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
cn103:5367:5367 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:10.11.0.103<0>
cn103:5367:5367 [1] NCCL INFO Using network IB
cn103:5367:5414 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
cn103:5367:5414 [1] NCCL INFO Channel 00 : 0[89000] -> 1[8a000] [receive] via NET/IB/0
cn103:5367:5414 [1] NCCL INFO Channel 01 : 0[89000] -> 1[8a000] [receive] via NET/IB/0
cn103:5367:5414 [1] NCCL INFO Channel 00 : 1[8a000] -> 0[89000] [send] via NET/IB/0
cn103:5367:5414 [1] NCCL INFO Channel 01 : 1[8a000] -> 0[89000] [send] via NET/IB/0
cn103:5367:5414 [1] NCCL INFO Connected all rings
cn103:5367:5414 [1] NCCL INFO Connected all trees
cn103:5367:5414 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
cn103:5367:5414 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
cn103:5367:5414 [1] NCCL INFO comm 0x7f1da8002010 rank 1 nranks 2 cudaDev 1 busId 8a000 - Init COMPLETE
```
Note that I don't get any `sockeye` related logs in the worker.

**Comment by mjdenkowski** [comment]
If all of the ports are open, NCCL should be able to create connections.

One other thing to try would be matching the software versions we used when investigating this issue.

PyTorch 1.11.0 built with CUDA 10.2 (current default version): `pip3 install torch` or `pip3 install torch==1.11.0`

Sockeye 3.1.9:
```
git clone https://github.com/awslabs/sockeye.git
cd sockeye
git checkout 71914bb222597d781b2144b8831421169b4247ee
pip3 install --editable ./
```

**Comment by SamuelLarkin** [comment]
For some reason, I was under the impression we python-1.10.0 was cuda11 or newer only.  I learned something today ;).

I've created a new conda environment to match your environment but I'm still getting the master to loop forever on `clock_gettime(CLOCK_MONOTONIC_RAW, {tv_sec=4222831, tv_nsec=568585236}) = 0`.

# Torchrun
```bash
time torchrun --no_python --nnodes=2 --nproc_per_node=1 --node_rank=0 --master_addr=10.10.0.104 --master_port=17196 --rdzv_id=94780 --rdzv_backend=c10d --rdzv_endpoint=10.10.0.104:17307 sockeye-train --dist --quiet-secondary-workers --config=model_config.yaml
time torchrun --no_python --nnodes=2 --nproc_per_node=1 --node_rank=1 --master_addr=10.10.0.104 --master_port=17196 --rdzv_id=94780 --rdzv_backend=c10d --rdzv_endpoint=10.10.0.104:17307 sockeye-train --dist --quiet-secondary-workers --config=model_config.yaml
```

# Sockeye
```bash
git branch -v
* debug 71914bb22 Clarify use of Translator.batch_size in code (#1033)
  main  71914bb22 Clarify use of Translator.batch_size in code (#1033)
```

```
[INFO:sockeye.utils] Sockeye: 3.1.9, commit unknown, path /home/larkins/git/sockeye/sockeye/__init__.py
[INFO:sockeye.utils] PyTorch: 1.11.0 (/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.9.debug/lib/python3.8/site-packages/torch/__init__.py)
```
# Conda Env
```
CONDA: sockeye-3.1.9.debug
name: sockeye-3.1.9.debug
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.3=h516909a_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h578d9bd_2
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.2=py38h578d9bd_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.2=py38h2b5fc30_1
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - cudnn=8.2.1.32=h2c0ae14_0
  - cxxfilt=0.3.0=py38h709712a_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - docutils=0.16=py38h578d9bd_3
  - expat=2.4.8=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.31.2=py38h0a891b7_1
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.3.0=py38h0a891b7_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - google-auth=2.6.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.45.0=py38ha0cdfde_0
  - gst-plugins-base=1.20.1=hcf0ee16_1
  - gstreamer=1.20.1=hd4edc92_1
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.3=py38h578d9bd_1
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.1.1=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py38h43d8883_1
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=13.0.1=default_hc23dcda_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_15
  - libglib=2.70.2=h174f98d_4
  - libiconv=1.16=h516909a_0
  - libllvm13=13.0.1=hf817b99_2
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - libprotobuf=3.20.0=h6239696_0
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib=3.5.1=py38h578d9bd_0
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - multidict=6.0.2=py38h0a891b7_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.28=haf5c9bc_3
  - mysql-libs=8.0.28=h28c427c_3
  - nccl=2.12.7.1=h1a5f58c_0
  - ncurses=6.3=h27087fc_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.77=h2350873_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - nvidia-apex=0.1=py38h3af061c_4
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1n=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.1.0=py38h0ee0e06_0
  - pip=22.0.4=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h578d9bd_3
  - protobuf=3.20.0=py38hfa26641_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - py=1.11.0=pyh6c4a22f_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.12.3=py38h578d9bd_8
  - pyqt-impl=5.12.3=py38h0ffb2e6_8
  - pyqt5-sip=4.19.18=py38h709712a_8
  - pyqtchart=5.12=py38h7400c14_8
  - pyqtwebengine=5.12.1=py38h7400c14_8
  - pysocks=1.7.1=py38h578d9bd_5
  - pytest=7.1.1=py38h578d9bd_1
  - python=3.8.13=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - qt=5.12.9=h1304e3e_6
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlite=3.37.1=h4ff8645_0
  - tbb=2021.5.0=h924138e_1
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py38h3e25421_1
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py38h0a891b7_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - unicodedata2=14.0.0=py38h0a891b7_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - werkzeug=2.1.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - ipython==8.2.0
    - portalocker==2.4.0
    - pudb==2022.1
    - sacrebleu==1.4.14
    - sentencepiece==0.1.96
    - subword-nmt==0.3.8
    - tabulate==0.8.9+computecanada
    - tokenizers==0.11.6
```

**Comment by mjdenkowski** [comment]
Unfortunately this may be as far as we can debug this issue.

As part of our investigation, we confirmed that distributed training runs as expected with the following setup:
- EC2 g4dn.xlarge instances running the [AWS Deep Learning Base AMI (Amazon Linux)](https://aws.amazon.com/marketplace/pp/prodview-vl4n7ldaufpg4)
- Security group opening all TCP ports among hosts
- PyTorch 1.11.0 built with CUDA 10.2
- Sockeye 3.1.9

At this point, we've matched the main software versions and it doesn't look like we have any actual error messages to work with.  Training on 4 local GPUs might be the best workaround for now.

As a side note, your initial issue report was helpful for identifying an issue that potentially affects other Sockeye users: NCCL's requiring fully unblocked TCP ports.  Thanks for your report!

**Comment by SamuelLarkin** [comment]
You provided great help!
Thanks

**Comment by mjdenkowski** [comment]
Closing this for now. You're welcome to reopen with any new information.
